"""
downloader.py — تحميل الفيديوهات من المواقع المحمية بـ Cloudflare

استراتيجيات متعددة (بالترتيب):
  1. yt-dlp مع impersonate + cookies
  2. curl_cffi مع impersonate
  3. FlareSolverr (يحل التحدي عبر متصفح حقيقي)
  4. curl_cffi + الكوكيز من FlareSolverr

يرفع DownloadError عند فشل كل الاستراتيجيات.
"""

import json
import os
import re
import subprocess
import time
from pathlib import Path
from urllib.parse import urlparse

import requests

from config import config, MEDIA_DIR
from errors import DownloadError


# ═══════════════════════════════════════════════════════════════
# الإعدادات من البيئة
# ═══════════════════════════════════════════════════════════════
IMPERSONATE_TARGET = os.environ.get("IMPERSONATE_TARGET", "chrome").strip()
FLARESOLVERR_URL = os.environ.get(
    "FLARESOLVERR_URL", "http://localhost:8191/v1"
).strip()
USE_FLARESOLVERR = os.environ.get("USE_FLARESOLVERR", "true").lower() == "true"

CHUNK_SIZE = 1024 * 1024        # 1MB للتحميل
YTDLP_TIMEOUT = 7200            # ساعتان
FS_TIMEOUT = 90000              # 90 ثانية لـ FlareSolverr
HTTP_TIMEOUT = 300              # 5 دقائق لكل طلب HTTP

# ملف كوكيز مؤقت
COOKIES_FILE = Path("/tmp/soo_cookies.txt")


# ═══════════════════════════════════════════════════════════════
# أدوات مساعدة
# ═══════════════════════════════════════════════════════════════
def _safe_name(name: str) -> str:
    """يُنظّف الاسم ليكون صالحاً كاسم ملف."""
    return re.sub(r'[\\/:*?"<>|]', "_", name).strip()[:120]


def _get_referer(url: str) -> str:
    """يُعيد الـ referer المناسب حسب الدومين."""
    try:
        parsed = urlparse(url)
        return f"{parsed.scheme}://{parsed.netloc}/"
    except Exception:
        return config.SOURCE_BASE_URL + "/"


def _save_cookies_from_flaresolverr(cookies: list) -> Path:
    """يحوّل كوكيز FlareSolverr إلى صيغة Netscape لـ yt-dlp."""
    COOKIES_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Netscape HTTP Cookie File",
        "# Auto-generated by downloader.py",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expiry", 0)) or int(time.time()) + 86400
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(
            f"{domain}\t{flag}\t{c.get('path', '/')}\t{secure}\t"
            f"{expires}\t{name}\t{value}"
        )
    COOKIES_FILE.write_text("\n".join(lines), encoding="utf-8")
    return COOKIES_FILE


# ═══════════════════════════════════════════════════════════════
# 1) yt-dlp
# ═══════════════════════════════════════════════════════════════
def _download_with_ytdlp(url: str, out_path: Path,
                          cookies_file: Path = None) -> bool:
    """
    يحمّل باستخدام yt-dlp مع impersonation.
    إذا مُرّر cookies_file، يستخدمه.
    """
    referer = _get_referer(url)

    cmd = [
        "yt-dlp",
        "--no-playlist",
        "--no-warnings",
        "--progress",
        "--newline",
        "--impersonate", IMPERSONATE_TARGET,
        "--extractor-args", f"generic:impersonate",
        "--user-agent", config.USER_AGENT,
        "--referer", referer,
        "--add-header", f"Origin:{referer.rstrip('/')}",
        "--retries", "3",
        "--fragment-retries", "3",
        "--socket-timeout", "60",
        "-f", "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/b[ext=webm]/b",
        "--merge-output-format", "mp4",
        "-o", str(out_path),
    ]

    if cookies_file and cookies_file.exists():
        cmd.extend(["--cookies", str(cookies_file)])

    cmd.append(url)

    # احذف أي ملف جزئي
    if out_path.exists():
        try:
            out_path.unlink()
        except Exception:
            pass

    print(f"    ↳ [1/4] yt-dlp --impersonate {IMPERSONATE_TARGET}"
          + (f" + cookies" if cookies_file else ""))

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=YTDLP_TIMEOUT,
        )

        if result.returncode == 0 and out_path.exists() and out_path.stat().st_size > 0:
            return True

        stderr = (result.stderr or "").strip()
        stdout = (result.stdout or "").strip()

        # اعرض آخر سطر مهم
        err_line = stderr.split("\n")[-1] if stderr else (stdout.split("\n")[-1] if stdout else "")
        if "403" in err_line or "Forbidden" in err_line:
            print(f"    ✗ yt-dlp: 403 Forbidden (Cloudflare)")
        elif "impersonate" in err_line.lower():
            print(f"    ✗ yt-dlp: impersonate غير متاح")
        else:
            print(f"    ✗ yt-dlp: {err_line[:200]}")

        return False

    except FileNotFoundError:
        print("    ✗ yt-dlp غير مثبت")
        return False
    except subprocess.TimeoutExpired:
        print("    ✗ yt-dlp تجاوز الوقت")
        return False
    except Exception as e:
        print(f"    ✗ yt-dlp خطأ: {e}")
        return False


# ═══════════════════════════════════════════════════════════════
# 2) curl_cffi (بدون كوكيز)
# ═══════════════════════════════════════════════════════════════
def _download_with_curl_cffi(url: str, out_path: Path,
                              cookies: dict = None) -> bool:
    """
    يحمّل مباشرة عبر curl_cffi مع impersonation.
    يفيد إذا كان الرابط يوجّه إلى ملف فيديو مباشر بعد إعادة توجيه.
    """
    try:
        from curl_cffi import requests as cffi_requests
    except ImportError:
        print("    ✗ curl_cffi غير مثبت")
        return False

    referer = _get_referer(url)
    headers = {
        "User-Agent": config.USER_AGENT,
        "Accept": "video/mp4,video/*;q=0.9,application/octet-stream;q=0.8,*/*;q=0.7",
        "Accept-Language": "ar,en;q=0.9",
        "Referer": referer,
        "Origin": referer.rstrip("/"),
    }

    print(f"    ↳ [2/4] curl_cffi (impersonate={IMPERSONATE_TARGET}"
          + (f", cookies={len(cookies)})" if cookies else ")"))

    try:
        # أولاً: HEAD لفحص النوع والحجم
        head = cffi_requests.head(
            url,
            headers=headers,
            cookies=cookies or {},
            impersonate=IMPERSONATE_TARGET,
            timeout=60,
            allow_redirects=True,
        )

        if head.status_code >= 400:
            print(f"    ✗ HEAD {head.status_code}")
            return False

        content_type = head.headers.get("content-type", "").lower()
        if not any(t in content_type for t in ("video", "octet-stream", "mp4", "mpeg")):
            print(f"    ✗ ليس فيديو مباشر: {content_type[:60]}")
            return False

        total_size = int(head.headers.get("content-length", 0))
        if total_size:
            print(f"       الحجم: {total_size / 1024 / 1024:.1f}MB")

        # ثانيًا: GET مع البث
        with cffi_requests.get(
            url,
            headers=headers,
            cookies=cookies or {},
            impersonate=IMPERSONATE_TARGET,
            stream=True,
            timeout=HTTP_TIMEOUT,
            allow_redirects=True,
        ) as r:
            r.raise_for_status()

            downloaded = 0
            last_report = 0

            with open(out_path, "wb") as f:
                for chunk in r.iter_content(chunk_size=CHUNK_SIZE):
                    if chunk:
                        f.write(chunk)
                        downloaded += len(chunk)

                        # اطبع كل 25MB
                        if downloaded - last_report >= 25 * CHUNK_SIZE:
                            last_report = downloaded
                            if total_size:
                                pct = downloaded / total_size * 100
                                print(f"       ... {downloaded / 1024 / 1024:.0f}MB "
                                      f"({pct:.0f}%)")
                            else:
                                print(f"       ... {downloaded / 1024 / 1024:.0f}MB")

        if out_path.exists() and out_path.stat().st_size > 0:
            return True
        return False

    except Exception as e:
        print(f"    ✗ curl_cffi: {type(e).__name__}: {str(e)[:150]}")
        return False


# ═══════════════════════════════════════════════════════════════
# 3) FlareSolverr
# ═══════════════════════════════════════════════════════════════
def _solve_with_flaresolverr(url: str) -> dict:
    """
    يطلب من FlareSolverr حل التحدي.
    يعيد: {cookies, user_agent, html, final_url} أو {} عند الفشل.
    """
    if not USE_FLARESOLVERR:
        print("    ✗ FlareSolverr معطّل (USE_FLARESOLVERR=false)")
        return {}

    payload = {
        "cmd": "request.get",
        "url": url,
        "maxTimeout": FS_TIMEOUT,
    }

    print(f"    ↳ [3/4] FlareSolverr: {FLARESOLVERR_URL}")

    try:
        r = requests.post(
            FLARESOLVERR_URL,
            json=payload,
            timeout=(FS_TIMEOUT / 1000) + 30,
        )
        data = r.json()
    except requests.exceptions.ConnectionError:
        print("    ✗ FlareSolverr غير متاح (Connection refused)")
        return {}
    except Exception as e:
        print(f"    ✗ FlareSolverr: {type(e).__name__}: {str(e)[:150]}")
        return {}

    if data.get("status") != "ok":
        msg = data.get("message", "unknown error")
        print(f"    ✗ FlareSolverr: {msg[:150]}")
        return {}

    solution = data.get("solution") or {}
    cookies = solution.get("cookies", [])
    ua = solution.get("userAgent", config.USER_AGENT)
    final_url = solution.get("url", url)
    html = solution.get("response", "")

    print(f"    ✓ FlareSolverr حل التحدي — {len(cookies)} كوكي، "
          f"{len(html) / 1024:.0f}KB HTML")

    return {
        "cookies": cookies,
        "user_agent": ua,
        "final_url": final_url,
        "html": html,
    }


def _extract_video_url_from_html(html: str) -> str:
    """
    يبحث عن رابط الفيديو المباشر داخل HTML.
    يدعم: <video src>, <source src>, iframe, JSON-LD, روابط .mp4
    """
    if not html:
        return ""

    patterns = [
        # <video src="...">
        r'<video[^>]+src=["\']([^"\']+\.(?:mp4|m3u8|webm)[^"\']*)["\']',
        # <source src="...">
        r'<source[^>]+src=["\']([^"\']+\.(?:mp4|m3u8|webm)[^"\']*)["\']',
        # iframe src
        r'<iframe[^>]+src=["\']([^"\']+)["\']',
        # data-src / data-video
        r'data-(?:src|video|url)=["\']([^"\']+\.(?:mp4|m3u8|webm)[^"\']*)["\']',
        # روابط .mp4 عامة
        r'["\'](https?://[^"\']+\.(?:mp4|m3u8|webm))["\']',
        # JSON: "file":"..."
        r'"file"\s*:\s*"([^"]+\.(?:mp4|m3u8|webm))"',
        r'"video_url"\s*:\s*"([^"]+)"',
        r'"source"\s*:\s*"([^"]+\.(?:mp4|m3u8)[^"]*)"',
    ]

    for pat in patterns:
        m = re.search(pat, html, re.IGNORECASE)
        if m:
            found = m.group(1)
            # تجاهل الروابط الوهمية
            if found.startswith("//"):
                found = "https:" + found
            if found.startswith(("http://", "https://")) and \
               not any(x in found for x in ("google", "facebook", "twitter", "ads")):
                return found

    return ""


# ═══════════════════════════════════════════════════════════════
# 4) الدالة الرئيسية
# ═══════════════════════════════════════════════════════════════
def download_episode(series: str, episode: int, url: str) -> Path:
    """
    يحمّل الحلقة باستخدام سلسلة استراتيجيات.
    يرفع DownloadError إذا فشل كل شيء.
    """
    safe_series = _safe_name(series)
    out_dir = MEDIA_DIR / safe_series
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"ep{episode:03d}.mp4"

    # ─── موجودة مسبقاً ───
    if out_path.exists() and out_path.stat().st_size > 0:
        mb = out_path.stat().st_size / 1024 / 1024
        print(f"    ↳ موجودة مسبقاً: {out_path.name} ({mb:.1f}MB)")
        return out_path

    print(f"    ↳ تحميل الحلقة {episode}: {url}")

    # ═══════════════════════════════════════════════════════
    # 1) yt-dlp (بدون كوكيز)
    # ═══════════════════════════════════════════════════════
    if _download_with_ytdlp(url, out_path):
        mb = out_path.stat().st_size / 1024 / 1024
        print(f"    ✅ تم التحميل (yt-dlp): {mb:.1f}MB")
        return out_path

    # ═══════════════════════════════════════════════════════
    # 2) curl_cffi (بدون كوكيز)
    # ═══════════════════════════════════════════════════════
    if _download_with_curl_cffi(url, out_path):
        mb = out_path.stat().st_size / 1024 / 1024
        print(f"    ✅ تم التحميل (curl_cffi): {mb:.1f}MB")
        return out_path

    # ═══════════════════════════════════════════════════════
    # 3) FlareSolverr — حل التحدي والحصول على كوكيز
    # ═══════════════════════════════════════════════════════
    fs_result = _solve_with_flaresolverr(url)

    if fs_result:
        # احفظ الكوكيز
        cookies_file = _save_cookies_from_flaresolverr(fs_result["cookies"])
        cookies_dict = {c["name"]: c["value"] for c in fs_result["cookies"]}
        html = fs_result.get("html", "")

        # ─── 3a) yt-dlp بالكوكيز ───
        if _download_with_ytdlp(url, out_path, cookies_file=cookies_file):
            mb = out_path.stat().st_size / 1024 / 1024
            print(f"    ✅ تم التحميل (yt-dlp + cookies): {mb:.1f}MB")
            return out_path

        # ─── 3b) ابحث عن رابط فيديو مباشر في HTML ───
        video_url = _extract_video_url_from_html(html)
        if video_url:
            print(f"    ↳ وُجد رابط فيديو في HTML: {video_url[:100]}...")

            # 3b-1) yt-dlp على الرابط المباشر
            if _download_with_ytdlp(video_url, out_path, cookies_file=cookies_file):
                mb = out_path.stat().st_size / 1024 / 1024
                print(f"    ✅ تم التحميل (رابط مباشر + yt-dlp): {mb:.1f}MB")
                return out_path

            # 3b-2) curl_cffi مع الكوكيز
            if _download_with_curl_cffi(video_url, out_path, cookies=cookies_dict):
                mb = out_path.stat().st_size / 1024 / 1024
                print(f"    ✅ تم التحميل (رابط مباشر + curl_cffi): {mb:.1f}MB")
                return out_path

        # ─── 3c) curl_cffi بالكوكيز على URL الأصلي ───
        if _download_with_curl_cffi(url, out_path, cookies=cookies_dict):
            mb = out_path.stat().st_size / 1024 / 1024
            print(f"    ✅ تم التحميل (curl_cffi + cookies): {mb:.1f}MB")
            return out_path

    # ═══════════════════════════════════════════════════════
    # فشل كل شيء
    # ═══════════════════════════════════════════════════════
    raise DownloadError(
        f"فشل تحميل {series} — الحلقة {episode}\n"
        f"   URL: {url}\n"
        f"   الاستراتيجيات المُجرّبة:\n"
        f"   1. yt-dlp --impersonate {IMPERSONATE_TARGET}\n"
        f"   2. curl_cffi --impersonate {IMPERSONATE_TARGET}\n"
        f"   3. FlareSolverr ({'متاح' if fs_result else 'فشل'})\n"
        f"\n"
        f"   تحقق من:\n"
        f"   - تشغيل FlareSolverr في automation.yml (services)\n"
        f"   - صحة الرابط: {url}"
    )


# ═══════════════════════════════════════════════════════════════
# اختبار سريع
# ═══════════════════════════════════════════════════════════════
if __name__ == "__main__":
    import sys

    test_url = sys.argv[1] if len(sys.argv) > 1 else (
        "https://u.3seq.com/video/modablaj-uzak-sehir-episode-141-rkoy/"
    )

    print("🧪 اختبار downloader.py")
    print(f"URL: {test_url}")
    print(f"IMPERSONATE: {IMPERSONATE_TARGET}")
    print(f"FLARESOLVERR: {FLARESOLVERR_URL}")
    print()

    try:
        path = download_episode("test", 1, test_url)
        print(f"\n✅ نجح: {path}")
    except DownloadError as e:
        print(f"\n❌ فشل:\n{e}")
        sys.exit(1)
